trigger:
  branches:
    include:
    - main
    - dev

pr:
  branches:
    include:
    - main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '1197439b-728b-4758-a54b-95d7768e16ea'
  imageRepository: 'hospitalmanagement'
  containerRegistry: 'hospitalmnmtacr-cucrb7avc6bgfpez.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

stages:

# Stage 1 - Always runs on dev AND main
- stage: Build
  displayName:  Build Docker Image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: '$(dockerfilePath)'
        tags: |
          $(tag)
          latest

# Stage 2 - Always runs on dev AND main
- stage: CodeAnalysis
  displayName:  Static Code Analysis
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Analysis
    displayName: SonarCloud Analysis
    steps:

    - task: JavaToolInstaller@0
      displayName: Install Java
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: SonarCloudPrepare@1
      displayName: Prepare SonarCloud
      inputs:
        SonarCloud: 'SonarCloudConnection'
        organization: 'magalimeviane'
        scannerMode: 'MSBuild'
        projectKey: 'magalimeviane_Hospital-Management'
        projectName: 'Hospital Management'

    - task: DotNetCoreCLI@2
      displayName: Build solution
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration Release'

    - task: SonarCloudAnalyze@1
      displayName: Run analysis

    - task: SonarCloudPublish@1
      displayName: Publish results
      inputs:
        pollingTimeoutSec: '300'

# Stage 3 - ONLY runs on main branch
- stage: Push
  displayName:  Push to ACR
  dependsOn: CodeAnalysis
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: Push
    displayName: Push image
    steps:
    - task: Docker@2
      displayName: Push to ACR
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: |
          $(tag)
          latest