apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hospital-app
  template:
    metadata:
      labels:
        app: hospital-app
    spec:
      containers:
      - name: hospital-app
        image: hospitalmnmtacr-cucrb7avc6bgfpez.azurecr.io/hospitalmanagement:latest
        ports:
        - containerPort: 7005