apiVersion: v1
kind: Service
metadata:
  name: hospital-app-service
  namespace: default
spec:
  selector:
    app: hospital-app
  ports:
  - port: 7005
    targetPort: 7005
  type: ClusterIP